# Prevent installation of packages, that are not older than 7 days for better security
npmMinimalAgeGate: 10080

# Creates a real, local node_modules folder in the project
nodeLinker: node-modules

# Forces Yarn to store the cache locally in the project (under .yarn/cache)
enableGlobalCache: false

# Standard compression for local cache files
compressionLevel: mixed
